# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# Hugo theme to use

baseURL = "https://samxiao.com/"
defaultContentLanguage = "en"

# When enabled a robots.txt file will be created in the site root that allows search engines to crawl the entire site
enableRobotsTXT = true

rssLimit = "25"

enableGitInfo = true

# The number of articles listed on each page of the article listing
paginate = 10

# The number of words that are used to generate the article summary when one is not provided in the front matter. A
# value of 0 will use the first sentence.
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  # Override default Hugo taxonomies
  tag = "tags"

[permalinks]
  posts = "/p/:filename/"

[frontmatter]
  # Fetches the date from the content file's filename
  date = [":filename", ":default"]